spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
#            directory:
#              root: ~/some-path/ default current dir
            analysis:
              configurer: class:vnu.uet.moonbe.config.MyLuceneAnalysisConfigurer
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 86400000 # a day # 60000 # a minute
      refresh-token:
        expiration: 604800000 # 7 days

url:
  base:
#    path: http://139.59.227.169:8080 # server
    path: http://localhost:8080 # local

file:
  upload:
#    path: /home/moonbe_quang/MoonApplication/Repo/file # server
    path: /home/ppvan/Downloads/temp-data # local

image:
  upload:
#    path: /home/moonbe_quang/MoonApplication/Repo/image # server
    path: /home/ppvan/Downloads/temp-data  # local

avatar:
  upload:
#    path: /home/moonbe_quang/MoonApplication/Repo/avatar # server
    path: /home/ppvan/Downloads/temp-data  # local

